GET http://localhost:3000/toDoList

###

GET http://localhost:3000/toDoList/5e3d21aa20b88b03f4721374

###

POST  http://localhost:3000/toDoList
Content-Type: application/json

{
    "Title": "Amir",
    "Date": "123",
    "IsDone": "false",
    "Description": "---",
    "PriorityType":"high"
}

###

DELETE http://localhost:3000/toDoList/5e3d21aa20b88b03f4721374

###

PATCH http://localhost:3000/toDoList/5e3a75f7698fb239602c0c1a
Content-Type: application/json

{
    "Title": "Amir2",
    "Date": "456",
    "IsDone": "true",
    "Description": "null",
    "PriorityType":"low"
}